recipe: Red Pasta Sauce

description: "Student's Milanese"
source: "Simon's dad"
date_created: 2018-11-19
last_updated: 2018-11-19
image: 

ingredients:
  - {id: 0, name: minced meat, amount: 400, unit: 'g', comment: ''}
  - {id: 1, name: chopped tomatoes, amount: 400, unit: 'g', comment: ''}
  - {id: 2, name: tomato paste, amount: 140, unit: 'g', comment: 'about 2 to 4 table spoons, to taste'}
  - {id: 3, name: onion, amount: 1, unit: 'g', comment: ''}
  - {id: 4, name: garlic, amount: 2, unit: 'cloves', comment: ''}
  - {id: 5, name: spinach leaves, amount: 100, unit: 'g', comment: ''}
  - {id: 6, name: mushrooms, amount: 1, unit: 'handfull', comment: ''}
  - {id: 7, name: chilli pepper, amount: 1, unit: 'piece', comment: ''}
  - {id: 8, name: basil, amount: 1, unit: 'tbsp', comment: ''}
  - {id: 9, name: oregano, amount: 1, unit: 'tbsp', comment: ''}
  - {id: 10, name: black pepper, amount: 2, unit: 'tsp', comment: ''}
  - {id: 11, name: salt, amount: 1, unit: 'tbsp', comment: 'to taste'}
  - {id: 12, name: paprika, amount: 1, unit: 'piece', comment: 'bell pepper'}
  # - {id: 13, name: , amount: , unit: 'g', comment: ''}
  # - {id: 14, name: , amount: , unit: 'g', comment: ''}
  # - {id: 15, name: , amount: , unit: 'g', comment: ''}
  # - {id: 16, name: , amount: , unit: 'g', comment: ''}
  # - {id: 17, name: , amount: , unit: 'g', comment: ''}
  # - {id: 18, name: , amount: , unit: 'g', comment: ''}
  # - {id: 19, name: , amount: , unit: 'g', comment: ''}
  # - {id: 20, name: , amount: , unit: 'g', comment: ''}
  # - {id: 21, name: , amount: , unit: 'g', comment: ''}

# types: bowl, fry, saucepan, pipe, oven, km (kitchen machine), cut, shape, bake, add, mortar
# colors: freeze (dark blue), cold (light blue), room (yellow), warm (orange), hot (red)
steps:
  - {id: 0, short: Cut paprika and mushrooms, time: 5, type: 'cut', temp: 'room',
     depends_on: [],
     ingredients: [ {id: 6}, {id: 12} ],
     long: "Chop and set aside the paprika and the mushrooms"}
  - {id: 1, short: , time: 1, type: '', temp: 'room',
     depends_on: [],
     ingredients: [ {id: 4}, {id: } ],
     long: ""}
  - {id: 2, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 3, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 4, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 5, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 6, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 7, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 8, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 9, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 10, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 11, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 12, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 13, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 14, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 15, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 16, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 17, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 18, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
  - {id: 19, short: , time: 1, type: '', temp: 'room',
     depends_on: [0],
     ingredients: [ {id: 0} ],
     long: ""}
