recipe: Onion Pizza

description: This pizza is great when you crave onion!

ingredients:
  - {name: onion, amount: 2, unit: '', comment: ''}
  - {name: butter, amount: 50, unit: 'gram', comment: ''}
  - {name: sugar, amount: 15, unit: 'gram', comment: ''}
  - {name: salt, amount: to taste, unit: '', comment: ''}
  - {name: pepper, amount: to taste, unit: '', comment: ''}
  - {name: shallot onion, amount: 2, unit: '', comment: ''}
  - {name: red onion, amount: 2 small, unit: '', comment: ''}
  - {name: leek, amount: a third, unit: '', comment: ''}
  - {name: garlic, amount: 5, unit: 'cloves', comment: ''}
  - {name: spring onion, amount: 2, unit: '', comment: ''}
  - {name: pizza dough, amount: 'one large', unit: '', comment: ''}
  - {name: red wine vinegar, amount: 50, unit: 'gram', comment: ''}
  - {name: sesame oil, amount: 'some', unit: '', comment: ''}
  - {name: cheese, amount: 12, unit: 'slices', comment: ''}

steps:
  - {id: 0, short: preheat the oven, time: 10, type: work, image: '',
  long: Preheat the oven to 220 degrees celsius.}
  - {id: 1, short: cut onions, time: 1, type: work, image: '',
  long: Start by cutting the onions into very thin slices.}
  - {id: 2, short: caramelize onions, time: 20, type: fry, image: '',
  long: Melt the butter in a pan on medium heat, 
  and add the onion. Add 10 grams of sugar. Season with salt and pepper.
  Change to medium low heat. Stir occasionally between the other steps.}
  - {id: 3, short: pickle the shallots, type: work, image: '',
  long: Cut the shallot onions into small chunks. Put them in a container
  and add the red wine vinegar and 5 gram of sugar.}
  - {id: 4, short: cut more onions, time: 6, type: work, image: '',
  long: Cut the red onions into chunks, the leek into rings and the garlic 
  into thin slices. Cut the spring onion into thin rings.}
  - {id: 5, short: assemble the pizza, time: 6, type: work, image: '',
  long: Put some baking paper on a baking tray. Pour on a generous layer of sesame oil.
  Lay the pizza dough on top of the oil. Press the spring onions into the dough.
  Spread the caramelized onions out on top. Add the pickled shallots and the garlic.
  Sprinkle the red onion and leek over.}
  - {id: 6, short: bake the pizza, time: 8, type: oven, image: '',
  long: Set the oven to lower heat, and put the baking tray with the pizza into the oven.}
  - {id: 7, short: add cheese, time: 1, type: work, image: '',
  long: Take the pizza out of the oven. Put the cheese on top. By waiting with adding
  the cheese, it will not be brown by the time the crust is done.}
  - {id: 8, short: bake more, time: 15, type: oven, image: '',
  long: Put the pizza back into the oven. After about 5 minutes, check on the pizza
  every once it a while. Take the pizza out of the oven when the crust is crispy 
  and the cheese has melted.}

order:
  0: []
  1: []
  2: [1]
  3: []
  4: []
  5: [2,3,4]
  6: [0,5]
  7: [6]
  8: [7]

