TODOs

* Recipe Card (Google)
** Generating JSON-LD
*** Decouple YAML from internal representation
*** Generate JSON from internal representation
** Update recipe information
*** Prep time, cook time, total time
*** Nutritial information
**** Create ingredients with info about allergies and content
Check the suitableForDiet section of the spec
**** Allow recipes to override the ingredient allergies
Example: Soy milk can be used instead of milk, without problems, in this recipe
**** Allow recipes to override the amount of an ingredient
Example: Deep-frying. Some oil will be left in the doughnuts, but most will remain in the pan
**** Read in ingredients-YAML to memory before recipes - internal representation?
**** Scan through ingredients when reading a recipe
*** Category
**** Dessert
*** Cuisine
**** What can I use here?
*** Keywords
*** Servings
*** isBasedOn
This already exists, but I should show it on the website
*** User rating - ignore this?
* Photo's added to steps
** Path to the photo
** Add to YAML template
** Find a way to show it on the site
* Alt-tags on images
** Update the YAML+template
** Add to the code
* Image aspect ratio's
Recipe cards need 16x9, 4x3 and 1x1
Pinterest needs "phone images" - possibly with text
Pinterest also uses alt-text as description
* Recipes consisting of multiple partial recipes
Dropdown box to select which recipes to use
This is not relevant until we have more recipes
* virtualenv
Since this in a python project, we should look into using virtualenv to manage our dependencies.

* Support for multiple distinct paragraphs in long description field

* Recipe steps: remove need to always add `{id: }`, when most recipes only need the numbers. The parser should be able to pick up on the special cases where amount has to be addittionally specifies.

* Error output form recipe compiling is daunting.

* Recipe steps with only short description show a `:` at the end of the line, even though there is nothing to put after.

* Recipe steps show the text `none:` in bold if there is no no short description.

* Recipe scaling
** By volume
Try to change cooking time based on heat equation
Need to add volume used to recipes
** By ingredient
I ended up with 472 g pumpkin - scale recipe after that
** By servings
Need to add a concept of servings first
* Small changes
*** fridge icon, freezer icon
*** Site description
For search engines; metric recipes with simple ingredients, realistic times and a personal touch
*** Tags/description for every recipe
*** Site-map for robots?
*** Contact email
*** Create a proper front page
*** AMP?
*** Research what goes into making "carousel structured data"
*** Hover/click on a timeline step shows the short description
*** Add functionality to "check for step done" on a recipe page
*** Research if I can optimize for "featured snippets"
*** Create a front page
*** Show the optional ingredient notes

*** Add credits to the recipes "adapted from"
*** Fill up the "Tags" section - or delete from the site
*** More detailed recipes
*** Step numbers in alt-text/description
*** Update the text on the About-page
